###############################################
##Creates the migration table
###############################################
DROP TABLE IF EXISTS MIGRATION_;
CREATE TABLE MIGRATION_
SELECT pr.PARTYROLE_ID, p.PARTY_ID, pr.CUSTOMERID_, pr.TYPE_ID
	, (SELECT ACCOUNTNUMBER_ FROM ACCOUNT_
		WHERE PRODUCT_ID IN ('655949824', '655949333')
		  AND 0 = IFNULL(DUPLICATE_, 0)
		  AND CUSTOMER_PORTFOLIO_ID = pr.PARTYROLE_ID) ERPST_ACC_NOS
	, (SELECT ACCOUNTNUMBER_ FROM ACCOUNT_
		WHERE PRODUCT_ID IN ('655949832') 
		  AND 0 = IFNULL(DUPLICATE_, 0)
		  AND CUSTOMER_PORTFOLIO_ID = pr.PARTYROLE_ID) ERPIMACCOUNTNUMBER_
	, (SELECT BROKERAGENUMBER_ FROM ACCOUNT_
		WHERE PRODUCT_ID IN ('655949824', '655949333') 
		  AND 0 = IFNULL(DUPLICATE_, 0)
		  AND CUSTOMER_PORTFOLIO_ID = pr.PARTYROLE_ID) LEGACYSTACCOUNTNUMBER_
	, (SELECT MONEYMARKETNUMBER_ FROM ACCOUNT_
		WHERE PRODUCT_ID IN ('655949832') 
		  AND 0 = IFNULL(DUPLICATE_, 0)
		  AND CUSTOMER_PORTFOLIO_ID = pr.PARTYROLE_ID) LEGACYMMACCOUNTNUMBER_
	, (SELECT TREASURYBILLNUMBER_ FROM ACCOUNT_
		WHERE PRODUCT_ID IN ('655949832')
		  AND 0 = IFNULL(DUPLICATE_, 0)
		  AND CUSTOMER_PORTFOLIO_ID = pr.PARTYROLE_ID) LEGACYTBILLSACCOUNTNUMBER_
	, pr.LEGACYNUMBER_ LEGACYCUSTOMERID_
	, p.PARTYTITLE_ID, p.FIRSTNAME_, p.MIDDLENAME_, p.LASTNAME_
	, p.INITIALS_, p.GENDER_ID, p.MARITALSTATUSTYPE_ID, p.MAIDENNAME_, p.DATEOFBIRTH_, p.PRIMARYEMAILADDRESS_
	, p.COUNTRY_ID, p.PRIMARYPHONENO_, p.WORKPHONENUMBER_, p.ADDRESSLINE1_, p.ADDRESSLINE2_, p.ADDRESSCITY_
	, p.ADDRESSSTATE_ID, p.ADDRESSCOUNTRY_ID, pr.KINRELATIONSHIPTYPE_ID, pr.KINFIRSTNAME_, pr.KINLASTNAME_
	, pr.KINOTHERNAMES_, pr.KINCONTACTPHONENUMBER_, pr.KINADDRESS_, pr.LOCALE_, p.FULLNAME_, pr.TOTALASSETVALUE_
	, pr.LASTACTIVITYDATE_
FROM PARTY_ p
	JOIN PARTYROLE_ pr 
	  ON p.PARTY_ID = pr.PARTY_ROLES_ID
WHERE pr.TYPE_ID IN (4,5);

ALTER TABLE MIGRATION_ ADD ISNAMEVALID_ bit(1) DEFAULT 0 AFTER TOTALASSETVALUE_;
ALTER TABLE MIGRATION_ ADD ISEMAILVALID_ bit(1) DEFAULT 0 AFTER ISNAMEVALID_;
ALTER TABLE MIGRATION_ ADD ISPHONENOVALID_ bit(1) DEFAULT 0 AFTER ISEMAILVALID_;
ALTER TABLE MIGRATION_ ADD ISADDRESSVALID_ bit(1) DEFAULT 0 AFTER ISPHONENOVALID_;
ALTER TABLE MIGRATION_ ADD ISCUSTOMERMAPPED_ bit(1) DEFAULT 0 AFTER ISADDRESSVALID_;
ALTER TABLE MIGRATION_ ADD ISDUPLICATE_ bit(1) DEFAULT 0 AFTER ISCUSTOMERMAPPED_;
ALTER TABLE MIGRATION_ ADD DUPLICATE_ID bigint(20) DEFAULT 0 AFTER ISDUPLICATE_;
ALTER TABLE MIGRATION_ ADD DATEMARKEDDUPLICATE_ DATETIME AFTER DUPLICATE_ID;
ALTER TABLE MIGRATION_ ADD CUSTOMERMIGRATIONSTATUS_ TINYINT(1) DEFAULT 0 AFTER DATEMARKEDDUPLICATE_;
ALTER TABLE MIGRATION_ ADD STACCOUNTMIGRATIONSTATUS_  TINYINT(1) DEFAULT 0 AFTER CUSTOMERMIGRATIONSTATUS_;
ALTER TABLE MIGRATION_ ADD MMACCOUNTMIGRATIONSTATUS_  TINYINT(1) DEFAULT 0 AFTER STACCOUNTMIGRATIONSTATUS_;
ALTER TABLE MIGRATION_ ADD TBILLSACCOUNTMIGRATIONSTATUS_  TINYINT(1) DEFAULT 0 AFTER MMACCOUNTMIGRATIONSTATUS_;
ALTER TABLE MIGRATION_ ADD VERSION_ bigint(20) DEFAULT 1 AFTER TBILLSACCOUNTMIGRATIONSTATUS_;
ALTER TABLE MIGRATION_ ADD LASTUPDATEDATE_ TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER VERSION_;
ALTER TABLE MIGRATION_ ADD LASTUPDATEBY_ VARCHAR(50) AFTER LASTUPDATEDATE_;

##########################################################################
# Creates table for holding statuses 
##########################################################################
DROP TABLE MIGRATIONSTATUS_;
CREATE TABLE MIGRATIONSTATUS_
SELECT PARTYROLE_ID, PARTY_ID, CUSTOMERID_, TYPE_ID, ERPST_ACC_NOS, ERPIMACCOUNTNUMBER_, LEGACYSTACCOUNTNUMBER_ 
	, LEGACYMMACCOUNTNUMBER_, LEGACYTBILLSACCOUNTNUMBER_, LEGACYCUSTOMERID_, PARTYTITLE_ID, FIRSTNAME_, MIDDLENAME_
	, LASTNAME_, INITIALS_, GENDER_ID, MARITALSTATUSTYPE_ID, MAIDENNAME_, DATEOFBIRTH_, PRIMARYEMAILADDRESS_
	, COUNTRY_ID, PRIMARYPHONENO_, WORKPHONENUMBER_, ADDRESSLINE1_, ADDRESSLINE2_, ADDRESSCITY_
	, ADDRESSSTATE_ID, ADDRESSCOUNTRY_ID, KINRELATIONSHIPTYPE_ID, KINFIRSTNAME_, KINLASTNAME_
	, KINOTHERNAMES_, KINCONTACTPHONENUMBER_, KINADDRESS_, LOCALE_, FULLNAME_, TOTALASSETVALUE_, LASTACTIVITYDATE_
FROM migration_ LIMIT 1;

TRUNCATE TABLE MIGRATIONSTATUS_;

ALTER TABLE MIGRATIONSTATUS_ ADD REJECTREASON_ VARCHAR(255) AFTER TOTALASSETVALUE_;
ALTER TABLE MIGRATIONSTATUS_ ADD DUPLICATE_IDS VARCHAR(50) AFTER REJECTREASON_;
ALTER TABLE MIGRATIONSTATUS_ ADD SUBMITDATE_ DATETIME DEFAULT NULL AFTER DUPLICATE_IDS;
ALTER TABLE MIGRATIONSTATUS_ ADD LASTUPDATEDATE_ TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER SUBMITDATE_;
ALTER TABLE MIGRATIONSTATUS_ ADD LASTUPDATEBY_ VARCHAR(50) AFTER LASTUPDATEDATE_;
ALTER TABLE MIGRATIONSTATUS_ ADD APPROVEDBY_ VARCHAR(50) DEFAULT NULL AFTER LASTUPDATEBY_;
ALTER TABLE MIGRATIONSTATUS_ ADD APPROVEDATE_ DATETIME DEFAULT NULL AFTER APPROVEDBY_;
ALTER TABLE MIGRATIONSTATUS_ ADD STATUS_ TINYINT(2) DEFAULT 0 AFTER APPROVEDATE_;
ALTER TABLE MIGRATIONSTATUS_ ADD COLUMN sn INT NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (sn);
#  STATUS_ values are 0 - Pending, 1 approved, 2 Rejected

###############################################################################
##Creates the triggers to pull inserted/updated records into the audit table
###############################################################################
DROP TRIGGER `ai_Migration_`;
DELIMITER $$
CREATE TRIGGER ai_Migration_
AFTER INSERT
ON `migration_` FOR EACH ROW
BEGIN
   INSERT INTO MIGRATIONAUDIT_
    	(
			PARTYROLE_ID, PARTY_ID, CUSTOMERID_, TYPE_ID, ERPST_ACC_NOS, ERPIMACCOUNTNUMBER_
			, LEGACYCUSTOMERID_, LEGACYMMACCOUNTNUMBER_, LEGACYTBILLSACCOUNTNUMBER_, PARTYTITLE_ID, FIRSTNAME_
			, MIDDLENAME_, LASTNAME_, INITIALS_, GENDER_ID, MARITALSTATUSTYPE_ID, MAIDENNAME_, DATEOFBIRTH_
			, PRIMARYEMAILADDRESS_, COUNTRY_ID, PRIMARYPHONENO_, WORKPHONENUMBER_, ADDRESSLINE1_, ADDRESSLINE2_
			, ADDRESSCITY_, ADDRESSSTATE_ID, ADDRESSCOUNTRY_ID, KINRELATIONSHIPTYPE_ID, KINFIRSTNAME_, KINLASTNAME_
			, KINOTHERNAMES_, KINCONTACTPHONENUMBER_, KINADDRESS_, LOCALE_, FULLNAME_, TOTALASSETVALUE_
			, ISNAMEVALID_, ISEMAILVALID_, ISPHONENOVALID_, ISADDRESSVALID_, ISCUSTOMERMAPPED_, ISDUPLICATE_
			, DUPLICATE_ID, DATEMARKEDDUPLICATE_, CUSTOMERMIGRATIONSTATUS_, STACCOUNTMIGRATIONSTATUS_
			, MMACCOUNTMIGRATIONSTATUS_, TBILLSACCOUNTMIGRATIONSTATUS_, VERSION_, LASTUPDATEDATE_, LASTUPDATEBY_
		)
   VALUES (
   			NEW.PARTYROLE_ID, NEW.PARTY_ID, NEW.CUSTOMERID_, NEW.TYPE_ID, NEW.ERPST_ACC_NOS, NEW.ERPIMACCOUNTNUMBER_
			, NEW.LEGACYCUSTOMERID_, NEW.LEGACYMMACCOUNTNUMBER_, NEW.LEGACYTBILLSACCOUNTNUMBER_, NEW.PARTYTITLE_ID, NEW.FIRSTNAME_
			, NEW.MIDDLENAME_, NEW.LASTNAME_, NEW.INITIALS_, NEW.GENDER_ID, NEW.MARITALSTATUSTYPE_ID, NEW.MAIDENNAME_, NEW.DATEOFBIRTH_
			, NEW.PRIMARYEMAILADDRESS_, NEW.COUNTRY_ID, NEW.PRIMARYPHONENO_, NEW.WORKPHONENUMBER_, NEW.ADDRESSLINE1_, NEW.ADDRESSLINE2_
			, NEW.ADDRESSCITY_, NEW.ADDRESSSTATE_ID, NEW.ADDRESSCOUNTRY_ID, NEW.KINRELATIONSHIPTYPE_ID, NEW.KINFIRSTNAME_, NEW.KINLASTNAME_
			, NEW.KINOTHERNAMES_, NEW.KINCONTACTPHONENUMBER_, NEW.KINADDRESS_, NEW.LOCALE_, NEW.FULLNAME_, NEW.TOTALASSETVALUE_
			, NEW.ISNAMEVALID_, NEW.ISEMAILVALID_, NEW.ISPHONENOVALID_, NEW.ISADDRESSVALID_, NEW.ISCUSTOMERMAPPED_, NEW.ISDUPLICATE_
			, NEW.DUPLICATE_ID, NEW.DATEMARKEDDUPLICATE_, NEW.CUSTOMERMIGRATIONSTATUS_, NEW.STACCOUNTMIGRATIONSTATUS_
			, NEW.MMACCOUNTMIGRATIONSTATUS_, NEW.TBILLSACCOUNTMIGRATIONSTATUS_, NEW.VERSION_, NEW.LASTUPDATEDATE_, NEW.LASTUPDATEBY_
		);
END$$
DELIMITER ;
####    Triggers definition continues...
DROP TRIGGER `au_Migration_`
DELIMITER //
CREATE TRIGGER au_Migration_
AFTER UPDATE
ON `migration_` FOR EACH ROW
BEGIN
   INSERT INTO MIGRATIONAUDIT_
    	(
			PARTYROLE_ID, PARTY_ID, CUSTOMERID_, TYPE_ID, ERPST_ACC_NOS, ERPIMACCOUNTNUMBER_
			, LEGACYCUSTOMERID_, LEGACYMMACCOUNTNUMBER_, LEGACYTBILLSACCOUNTNUMBER_, PARTYTITLE_ID, FIRSTNAME_
			, MIDDLENAME_, LASTNAME_, INITIALS_, GENDER_ID, MARITALSTATUSTYPE_ID, MAIDENNAME_, DATEOFBIRTH_
			, PRIMARYEMAILADDRESS_, COUNTRY_ID, PRIMARYPHONENO_, WORKPHONENUMBER_, ADDRESSLINE1_, ADDRESSLINE2_
			, ADDRESSCITY_, ADDRESSSTATE_ID, ADDRESSCOUNTRY_ID, KINRELATIONSHIPTYPE_ID, KINFIRSTNAME_, KINLASTNAME_
			, KINOTHERNAMES_, KINCONTACTPHONENUMBER_, KINADDRESS_, LOCALE_, FULLNAME_, TOTALASSETVALUE_
			, ISNAMEVALID_, ISEMAILVALID_, ISPHONENOVALID_, ISADDRESSVALID_, ISCUSTOMERMAPPED_, ISDUPLICATE_
			, DUPLICATE_ID, DATEMARKEDDUPLICATE_, CUSTOMERMIGRATIONSTATUS_, STACCOUNTMIGRATIONSTATUS_
			, MMACCOUNTMIGRATIONSTATUS_, TBILLSACCOUNTMIGRATIONSTATUS_, VERSION_, LASTUPDATEDATE_, LASTUPDATEBY_
		)
   VALUES (
   			NEW.PARTYROLE_ID, NEW.PARTY_ID, NEW.CUSTOMERID_, NEW.TYPE_ID, NEW.ERPST_ACC_NOS, NEW.ERPIMACCOUNTNUMBER_
			, NEW.LEGACYCUSTOMERID_, NEW.LEGACYMMACCOUNTNUMBER_, NEW.LEGACYTBILLSACCOUNTNUMBER_, NEW.PARTYTITLE_ID, NEW.FIRSTNAME_
			, NEW.MIDDLENAME_, NEW.LASTNAME_, NEW.INITIALS_, NEW.GENDER_ID, NEW.MARITALSTATUSTYPE_ID, NEW.MAIDENNAME_, NEW.DATEOFBIRTH_
			, NEW.PRIMARYEMAILADDRESS_, NEW.COUNTRY_ID, NEW.PRIMARYPHONENO_, NEW.WORKPHONENUMBER_, NEW.ADDRESSLINE1_, NEW.ADDRESSLINE2_
			, NEW.ADDRESSCITY_, NEW.ADDRESSSTATE_ID, NEW.ADDRESSCOUNTRY_ID, NEW.KINRELATIONSHIPTYPE_ID, NEW.KINFIRSTNAME_, NEW.KINLASTNAME_
			, NEW.KINOTHERNAMES_, NEW.KINCONTACTPHONENUMBER_, NEW.KINADDRESS_, NEW.LOCALE_, NEW.FULLNAME_, NEW.TOTALASSETVALUE_
			, NEW.ISNAMEVALID_, NEW.ISEMAILVALID_, NEW.ISPHONENOVALID_, NEW.ISADDRESSVALID_, NEW.ISCUSTOMERMAPPED_, NEW.ISDUPLICATE_
			, NEW.DUPLICATE_ID, NEW.DATEMARKEDDUPLICATE_, NEW.CUSTOMERMIGRATIONSTATUS_, NEW.STACCOUNTMIGRATIONSTATUS_
			, NEW.MMACCOUNTMIGRATIONSTATUS_, NEW.TBILLSACCOUNTMIGRATIONSTATUS_, NEW.VERSION_, NEW.LASTUPDATEDATE_, NEW.LASTUPDATEBY_
		);
END//
DELIMITER ;
###################################################
##Creates audit table for the migration table
###################################################
DROP TABLE IF EXISTS MIGRATIONAUDIT_;
CREATE TABLE MIGRATIONAUDIT_
SELECT * FROM MIGRATION_;
###################################################
# Creates table for reporting
###################################################
DROP TABLE IF EXISTS MIGRATIONREPORT_;
CREATE TABLE `MIGRATIONREPORT_` (
	`SN` int(11) NOT NULL auto_increment,
	`iBROKERCUSTOMERCOUNT_` int(11) default NULL,
	`iBROKERTBILLSACCOUNTCOUNT_` int(11) default NULL,
	`iBROKERSTACCOUNTCOUNT_` int(11) default NULL,
	`iBROKERMMACCOUNTCOUNT_` int(11) default NULL,
	`ERPCUSTOMERCOUNT_` int(11) default NULL,
	`LEGACYCUSTOMERCOUNT_` int(11) default NULL,
	`ERPTBILLSACCOUNTCOUNT_` int(11) default NULL,
	`ERPSTACCOUNTCOUNT_` int(11) default NULL,
	`ERPMMACCOUNTCOUNT_` int(11) default NULL,
	`LEGACYSTACCOUNTCOUNT_` int(11) default NULL,
	`LEGACYTBILLSACCOUNTCOUNT_` int(11) default NULL,
	`LEGACYMMACCOUNTCOUNT_` int(11) default NULL,
	`ERPSTCUSTOMERCOUNT_` int(11) default NULL,
	`ERPCLEANPHONECOUNT_` int(11) default NULL,
	`ERPCLEANEMAILCOUNT_` int(11) default NULL,
	`ERPCLEANADDRESSCOUNT_` int(11) default NULL,
	`ERPCLEANNAMESCOUNT_` int(11) default NULL,
	`ERPCUSTOMERREADYFORMIGRATION_` int(11) default NULL,
	`ERPCUSTOMERMIGRATEDCOUNT_` int(11) default NULL,
	`STACCOUNTREADYFORMIGRATION_` int(11) default NULL,
	`STACCOUNTMIGRATEDCOUNT_` int(11) default NULL,
	`MMACCOUNTREADYFORMIGRATION_` int(11) default NULL,
	`MMACCOUNTMIGRATEDCOUNT_` int(11) default NULL,
	`TBILLSACCOUNTREADYFORMIGRATION_` int(11) default NULL,
	`TBILLSACCOUNTMIGRATEDCOUNT_` int(11) default NULL,
	`CREATED_` datetime default NULL,
	`MODIFIED_` timestamp NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
	PRIMARY KEY  (`SN`)
)
