<?php

/*
* Create an empty array to store constants
*/
$C = array();
/*
* The database host URL
*/
$C['DB_HOST'] = '192.168.2.14'; //  192.168.2.14 - localhost - 192.168.2.17;
/*
* The database username
*/
$C['DB_USER'] = 'root';	
/*
* The database password
*/
$C['DB_PASS'] =  'acorn'; //	'acorn';
/*
* The port authentication is listening on
*/
$C['DB_AUTH_PORT'] =  '8080'; //	8080-Prod ; 8082-Dev;
/*
* The name of the database to work with
*/
$C['DB_NAME'] = 'chapelhill';// chapelhill  - oms3 - prod7Aug - chapelhilloct2;
/*
SELECT m1.PARTYROLE_ID, m1.PARTY_ID, m1.CUSTOMERID_, m1.TYPE_ID, m1.ST_ACC_NOS, m1.ST_ACC_TYPE_ID
	, m1.MoneyMarketPortfolio_, m1.LEGACYCUSTOMERID_, m1.LEGACYSTACCOUNTNUMBER_, m1.LEGACYMMACCOUNTNUMBER_
	, m1.LEGACYTBILLSACCOUNTNUMBER_, m1.PARTYTITLE_ID, m1.FIRSTNAME_, m1.MIDDLENAME_, m1.LASTNAME_
	, m1.INITIALS_, m1.GENDER_ID, m1.MARITALSTATUSTYPE_ID, m1.MAIDENNAME_, m1.DATEOFBIRTH_, m1.PRIMARYEMAILADDRESS_
	, m1.COUNTRY_ID, m1.PRIMARYPHONENO_, m1.WORKPHONENUMBER_, m1.ADDRESSLINE1_, m1.ADDRESSLINE2_, m1.ADDRESSCITY_
	, m1.ADDRESSSTATE_ID, m1.ADDRESSCOUNTRY_ID, m1.KINRELATIONSHIPTYPE_ID, m1.FIRSTNAME_, m1.LASTNAME_
	, m1.KINOTHERNAMES_, m1.KINCONTACTPHONENUMBER_, m1.KINADDRESS_, m1.LOCALE_, m1.FULLNAME_, m1.TOTALASSETVALUE_
	, m1.ISEMAILVALID_, m1.ISPHONENOVALID_, m1.ISVALIDADDRESS_, m1.ISCUSTOMERMAPPED_, m1.ISSTACCOUNTMAPPED_
	, m1.ISDUPLICATE_, m1.DUPLICATE_ID, m1.DATEMARKEDDUPLICATE_, m1.LASTUPDATEDATE_, m1.LASTUPDATEBY_, m1.MIGRATED_
	, m1.VERSION_, m1.LASTACTIVITYDATE_
FROM migration_ m1
	JOIN migration_ m2
		ON (
			IFNULL(m1.FIRSTNAME_, 0) = IFNULL(m2.FIRSTNAME_, 0)
			AND IFNULL(m1.MIDDLENAME_, 0) = IFNULL(m2.MIDDLENAME_, 0)
			AND IFNULL(m1.LASTNAME_,0) = IFNULL(m2.LASTNAME_,0)
			AND IFNULL(m1.PRIMARYEMAILADDRESS_,0) = IFNULL(m2.PRIMARYEMAILADDRESS_,0)
			AND IFNULL(m1.ADDRESSCOUNTRY_ID,0) = IFNULL(m2.ADDRESSCOUNTRY_ID,0)
			AND IFNULL(m1.FULLNAME_,0) = IFNULL(m2.FULLNAME_,0)
		)
WHERE m1.PARTYROLE_ID<> m2.PARTYROLE_ID
	AND  m1.CUSTOMERID_ <> m2.CUSTOMERID_
ORDER BY FIRSTNAME_
;
SELECT * FROM `migration_`
WHERE fullname_ like '%Adebola%Onadeko%'
SELECT * FROM `account_`
WHERE `CUSTOMER_PORTFOLIO_ID` IN ('655851744','655852160','660963346')

UPDATE `migration_` SET `ISDUPLICATE_`= b'0' WHERE `PARTYROLE_ID` IN ('655851744','655852160','660963346')
SELECT * FROM `account_` SET `ISDUPLICATE_`= b'0' WHERE `PARTYROLE_ID` IN ('655851744','655852160','660963346')
*/
?>
